### ISSUE TITLE
Support modules

### ISSUE THREAD

**Issue by bakkot** [bakkot/test262-web-runner#2]
Now shipping in FF and Safari nightlies, so it's time.

**Comment by littledan** [comment]
Ping, @GeorgNeis ran into this issue as well, in trying to test modules in Chrome.

**Comment by bakkot** [comment]
@littledan Good to know, I'll try to prioritize it. I got behind with the changes in the API and haven't had time to update in far too long.

**Comment by bakkot** [comment]
Extremely initial support landed, with no support for `import`. Next step is a service worker to intercept module load requests. That will take a bit longer, since I haven't done much with service workers.

Already found [a Chrome bug](https://bugs.chromium.org/p/v8/issues/detail?id=6516), though!

**Comment by bakkot** [comment]
Finally got around to this - see #5. Sorry that it took so long to get to what amounts to less than a hundred lines of code.

**Comment by GeorgNeis** [comment]
Nice!
